
development:
  adapter: postgresql
  database: hotspotter_development
  host: localhost
  pool: 16

test:
  adapter: postgresql
  database: hotspotter_test
  host: localhost
  pool: 16
  # timeout: 5000

production:
  adapter: postgresql
  database: hotspotter_production
  host: localhost
  pool: 16
  # timeout: 5000
