
development:
  adapter: postgresql
  database: hotspotter_development
  host: localhost

test:
  adapter: postgresql
  database: hotspotter_test
  host: localhost
  # pool: 5
  # timeout: 5000

production:
  adapter: postgresql
  database: hotspotter_production
  host: localhost
  # pool: 5
  # timeout: 5000
