
development:
  adapter: postgresql
  database: finalProject_development
  host: localhost

test:
  adapter: postgresql
  database: finalProject_test
  host: localhost
  # pool: 5
  # timeout: 5000

production:
  adapter: postgresql
  database: finalProject_production
  host: localhost
  # pool: 5
  # timeout: 5000
